on:
  push:
    tags: ["v*"]
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            override: true
            components: rustfmt, clippy
            target: x86_64-unknown-linux-gnu
      - uses: Swatinem/rust-cache@v1
      - run: cargo build --release --target x86_64-unknown-linux-gnu
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: target/x86_64-unknown-linux-gnu/release/md-img-to-table
